	FROM debian:latest
EXPOSE 7777/tcp
COPY --chown=root:root etc/docker/build      /root/build
COPY --chown=root:root etc/docker/entrypoint /root/entrypoint

RUN ["/bin/bash", "/root/build" ]
ENTRYPOINT [ "/bin/bash", "/root/entrypoint" ]
