#!/bin/bash
user=$1;
if [[ "$user" == "" ]] ;then user=33; fi

userdel simpledav;
rm -rf /home/simpledav
useradd simpledav -u$user -o

mkdir -p /tmp/nginx
/etc/init.d/nginx restart
while : ; do sleep 3600; done
